### ISSUE TITLE
The container launches multiple mysqld processes in a loop

### ISSUE THREAD

**Issue by onnimonni** [Painted-Fox/docker-mariadb#9]
I have multiple problems when mapping this to another port than the default 3306. I'm using the 3307 port instead.
When I do this container starts multiple processes and won't allow logging in.
`$ mysql -u super --password=J8s0hY0d6QJsOfF0 --protocol=tcp --port=3307`
`ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

**Comment by Painted-Fox** [comment]
Yes, you certainly can.  When you run the container try adding this flag: `-p 3307:3306`.  This means the container's port 3306 will be exposed on the host's 3307 port.  There's mor information on this in Docker's documentation section on [exposing incoming ports](http://docs.docker.io/reference/run/#expose-incoming-ports).

Is this what you mean?  It's more difficult to change the port the container will use internally.

**Comment by onnimonni** [comment]
Yeah I figured that out, thanks. What about the multiple mysqld processes this launches? I think there's some bug in my instance and it starts the mysqld process in loop.

``` bash
$ sudo docker run -d -name="mariadb" \
>              -p 127.0.0.1:3306:3306 \
>              -v /tmp/mariadb:/data \
>              -e USER="super" \
>              -e PASS="$(pwgen -s -1 16)" \
>              paintedfox/mariadb
Warning: '-name' is deprecated, it will be replaced by '--name' soon. See usage.
c11ccb25864ad8b1e577438ca1defe3c39290d3dac1bc6e82054c53aab1689d9
 $ sudo docker logs mariadb
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 10
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:09 mysqld_safe Logging to syslog.
140521 14:42:09 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:09 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:10 mysqld_safe Logging to syslog.
140521 14:42:10 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:10 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:12 mysqld_safe Logging to syslog.
140521 14:42:12 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:12 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:13 mysqld_safe Logging to syslog.
140521 14:42:13 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:14 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:15 mysqld_safe Logging to syslog.
140521 14:42:15 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:15 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:17 mysqld_safe Logging to syslog.
140521 14:42:17 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:17 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:18 mysqld_safe Logging to syslog.
140521 14:42:18 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:18 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:20 mysqld_safe Logging to syslog.
140521 14:42:20 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:20 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:21 mysqld_safe Logging to syslog.
140521 14:42:22 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:22 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
140521 14:42:23 mysqld_safe Logging to syslog.
140521 14:42:23 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
140521 14:42:23 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
MARIADB_USER=super
MARIADB_PASS=rAMioE88zEw1uFS4
MARIADB_DATA_DIR=/data
Starting MariaDB...
```

**Comment by onnimonni** [comment]
My version is:

``` bash
$ sudo docker version
Client version: 0.9.1
Go version (client): go1.2.1
Git commit (client): 3600720
Server version: 0.9.1
Git commit (server): 3600720
Go version (server): go1.2.1
Last stable version: 0.11.1, please update docker
```

**Comment by Painted-Fox** [comment]
Oh crud!  That's a problem.

**Comment by Painted-Fox** [comment]
What command are you using to start your container?  Would you happen to be using Vagrant?

**Comment by onnimonni** [comment]
I'm using the command shown in the earlier comment. My system is ubuntu 14.04 and I downloaded the mariadb container image straight from docker index.
`Linux kd3 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by renato-zannon** [comment]
I wasn't able to reproduce this (using the very same command) on docker 0.11.1

@onnimonni could you retry with the latest docker? Also, what are the contents of your `/tmp/mariadb` folder before running the command?

**Comment by Painted-Fox** [comment]
I was not able to reproduce the server trying to start over and over either.

However, I've found out a likely reason why you weren't able to connect to MariaDB and I fixed this with the latest change I made.  Essentially `sed` was not having an effect on the configuration file after the configuration directory was included in the `VOLUME` statement.  This meant that the container would bind to 127.0.0.1 (the default) and not accept any incoming connections from other sources.

Are you able to upgrade your docker version?

**Comment by onnimonni** [comment]
I'm not sure how to do that. Ubuntu says latest package is 0.9.1.

I tried with latest docker server binary (0.11) but with earlier docker client (0.9.1). I deleted the files in mariadb directory and started the container again. The results were still the same.
I have been using this container in other servers successfully many times. Strange that this is happening since docker shouldn't be depending on environment

**Comment by onnimonni** [comment]
Ok I managed to install reinstall docker with the latest but still getting loop error

**Comment by Painted-Fox** [comment]
Thank you very much for updating docker and verifying that it still happens.  I'm unfortunately unable to reproduce the loop error still, however.  Could you possibly verify that we've pulled the same image?  The latest image id is `3769a588bdac`.

```
fox@Squeak:~/proj/docker-mariadb$ docker images paintedfox/mariadb
REPOSITORY           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
paintedfox/mariadb   latest              3769a588bdac        19 hours ago        544.6 MB
```

As far as environment goes, sometimes I've noticed differences when people use Vagrant, but you're right, it shouldn't make a difference.  Most of the time I'll check [the docker index](https://index.docker.io/) and see that my Trusted Build failed for some reason, so people are pulling an old version, or that a build from there behaves slightly different from one that I've built myself.

I'm sorry you're experiencing this error.  How many servers do you have running `paintedfox/mariadb`?  I'm excited to hear that you're using it.

**Comment by zar29** [comment]
I am experiencing the same issue, I think it's related to the custom init system the phusion base image uses. I'm on 14.04 with the following docker version: 0.9.1, build 3600720.

I have been using this in production but was foolish enough to update it without testing it thoroughly first, does anyone know how I can fix this?

**Comment by Painted-Fox** [comment]
I made a change to avoid using _runit_, the phusion base image's init system for services.  If you do a `docker pull` you should get the change and the image id is `97b9f9cc2abb`.

@heyimwill I'm sorry my changes broke your production system.  Could you let me know if this fixes the issue?

**Comment by richardcrichardc** [comment]
I have also had trouble with paintedfox/mariadb on Ubuntu 14.04. I have tried with both Docker 0.9.1 which comes with 14.04 and 0.10 from Docker's Ubuntu repos. This is the error I got:

```
May 28 00:07:03 4df6c7e6d953 mysqld_safe: Starting mysqld daemon with databases from /data
May 28 00:07:03 4df6c7e6d953 mysqld: 140528  0:07:03 [ERROR] mysqld: File '/var/log/mysql/mariadb-bin.index' not found (Errcode: 13)
May 28 00:07:03 4df6c7e6d953 mysqld: 140528  0:07:03 [ERROR] Aborting
```

So I tried a different Docker image for (this time for MySQL) and had similar issues. Not sure if it was exactly the same as I could not see where the Mysql log was in the other container.

Finally I have switched to CoreOS from Ubuntu as the Docker host and paintedfox/mariadb just works. So I think this is a Ubuntu problem. I'm looking forward to when Docker has a stable release.

**Comment by richardcrichardc** [comment]
OK. I can get paintedfox/mariadb running on Ubuntu 14.04 if I switch the Docker storage driver to devicemapper.

**Comment by Painted-Fox** [comment]
@richardcrichardc Thank you for investigating!  I'm using Ubuntu 13.10 x64 on Digital Ocean to develop and test this image with Docker v0.11.1 from Docker's Ubuntu repo.

I'm able to reproduce that error message you saw when I add the flag `-v /tmp/mariadb/log:/var/log/mysql`.  I have to start MariaDB with `exec /usr/bin/mysqld_safe --skip-syslog --log-error=/data/mysql.log` since it appears to shut down before logging to syslog.

I get the `File '/var/log/mysql/mariadb-bin.index' not found` message since `/tmp/mariadb/log` on my host machine doesn't have that file.  Is this the case for you?

Unfortunately, right now the binary logs are mixed with the error logs so we'll run into this when trying to log to a folder on the host machine.  I've been thinking on a good way to separate these.

**Comment by richardcrichardc** [comment]
@Painted-Fox Given that I am finding the image works with devicemapper as the storage engine, but not AUFS I'm guessing the issue is related to this https://github.com/dotcloud/docker/issues/783. 

Does this seem right to you?

**Comment by richardcrichardc** [comment]
@painted-fox I missed your question:
I get the File '/var/log/mysql/mariadb-bin.index' not found message since /tmp/mariadb/log on my host machine doesn't have that file. Is this the case for you?

As far as I can see /var/log/mysql/mariadb-bin.index is there. Here is exactly what I did. You will see I have upgraded to 0.11.1:

```
root@trusty:/home/richardc# docker --version
Docker version 0.11.1, build fb99f99
root@trusty:/home/richardc# docker info
Containers: 0
Images: 27
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 27
Execution Driver: native-0.2
Kernel Version: 3.13.0-27-generic
WARNING: No swap limit support
root@trusty:/home/richardc# 
root@trusty:/home/richardc# docker run --name=mariadb paintedfox/mariadb
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 7
*** Running /scripts/start.sh...
MARIADB_USER=super
MARIADB_PASS=xBd7kKgO2nKr0Xim
MARIADB_DATA_DIR=/data
Initializing MariaDB at /data
Starting MariaDB...
140528 22:54:51 mysqld_safe Logging to syslog.
140528 22:54:51 mysqld_safe Starting mysqld daemon with databases from /data
140528 22:54:51 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
*** /scripts/start.sh exited with status 0.
*** Shutting down runit daemon (PID 7)...
*** Killing all processes...
root@trusty:/home/richardc# 
root@trusty:/home/richardc# docker commit mariadb dead
57208deb5a453c3ee4c338fc81fa76a67d5e31cd20f5c5255b40f28ca7de0f0e
root@trusty:/home/richardc# 
root@trusty:/home/richardc# docker run -i -t dead /bin/bash
root@6883dd49d804:/# 
root@6883dd49d804:/# cat /var/log/mysql
mysql/     mysql.err  mysql.log  
root@6883dd49d804:/# cat /var/log/mysql.log 
root@6883dd49d804:/# 
root@6883dd49d804:/# cat /var/log/daemon.log 
May 28 22:54:51 9e90ac2ed00b mysqld_safe: Starting mysqld daemon with databases from /data
May 28 22:54:51 9e90ac2ed00b mysqld: 140528 22:54:51 [ERROR] mysqld: File '/var/log/mysql/mariadb-bin.index' not found (Errcode: 13)
May 28 22:54:51 9e90ac2ed00b mysqld: 140528 22:54:51 [ERROR] Aborting
May 28 22:54:51 9e90ac2ed00b mysqld: 
May 28 22:54:51 9e90ac2ed00b mysqld: 140528 22:54:51 [Note] /usr/sbin/mysqld: Shutdown complete
May 28 22:54:51 9e90ac2ed00b mysqld: 
May 28 22:54:51 9e90ac2ed00b mysqld_safe: mysqld from pid file /var/run/mysqld/mysqld.pid ended
root@6883dd49d804:/# 
root@6883dd49d804:/# ls -l /var/log/mysql/
total 1064
-rw-rw---- 1 mysql adm   29077 May 26 18:16 mariadb-bin.000001
-rw-rw---- 1 mysql adm 1038814 May 26 18:16 mariadb-bin.000002
-rw-rw---- 1 mysql adm     439 May 26 18:16 mariadb-bin.000003
-rw-rw---- 1 mysql adm    1177 May 26 18:16 mariadb-bin.000004
-rw-rw---- 1 mysql adm     264 May 26 18:16 mariadb-bin.000005
-rw-rw---- 1 mysql adm     170 May 26 18:16 mariadb-bin.index
root@6883dd49d804:/# 

```

If I switch the Storage Driver to devicemapper by adding `DOCKER_OPTS="-s=devicemapper"` to `/etc/deafult/docker.io` then restarting the docker service the problem goes away:

```
root@trusty:/home/richardc# docker info
Containers: 2
Images: 26
Storage Driver: devicemapper
 Pool Name: docker-8:1-295118-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 926.5 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 2.0 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.13.0-27-generic
WARNING: No swap limit support
root@trusty:/home/richardc# 
root@trusty:/home/richardc# docker run --name=mariadb2 paintedfox/mariadb
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 7
*** Running /scripts/start.sh...
MARIADB_USER=super
MARIADB_PASS=gxd3noSV8Drk0tcr
MARIADB_DATA_DIR=/data
Initializing MariaDB at /data
Starting MariaDB...
140528 23:04:03 mysqld_safe Logging to syslog.
140528 23:04:03 mysqld_safe Starting mysqld daemon with databases from /data
^C*** Shutting down /scripts/start.sh (PID 8)...
140528 23:04:45 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
*** Shutting down runit daemon (PID 7)...
*** Killing all processes...
root@trusty:/home/richardc# docker commit mariadb2 good
707487859caadbc0d3daf9848e28335c549af3219afbd5c0eb248cc29d714802
root@trusty:/home/richardc# 
root@trusty:/home/richardc# docker run -i -t good /bin/bash
root@69f7d4b0dcd8:/# 
root@69f7d4b0dcd8:/# cat /var/log/daemon.log 
May 28 23:04:03 df1ed50de39e mysqld_safe: Starting mysqld daemon with databases from /data
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04 InnoDB: The InnoDB memory heap is disabled
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04 InnoDB: Mutexes and rw_locks use GCC atomic builtins
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04 InnoDB: Compressed tables use zlib 1.2.8
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04 InnoDB: Using Linux native AIO
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04 InnoDB: Initializing buffer pool, size = 128.0M
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04 InnoDB: Completed initialization of buffer pool
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: The first specified data file ./ibdata1 did not exist:
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: a new database to be created!
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04  InnoDB: Setting file ./ibdata1 size to 10 MB
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Database physically writes the file full: wait...
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Setting log file ./ib_logfile0 size to 5 MB
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Database physically writes the file full: wait...
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Setting log file ./ib_logfile1 size to 5 MB
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Database physically writes the file full: wait...
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Doublewrite buffer not found: creating new
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Doublewrite buffer created
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: 127 rollback segment(s) active.
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Creating foreign key constraint system tables
May 28 23:04:04 df1ed50de39e mysqld: InnoDB: Foreign key constraint system tables created
May 28 23:04:04 df1ed50de39e mysqld: 140528 23:04:04  InnoDB: Waiting for the background threads to start
May 28 23:04:05 df1ed50de39e mysqld: 140528 23:04:05 Percona XtraDB (http://www.percona.com) 5.5.37-MariaDB-34.0 started; log sequence number 0
May 28 23:04:05 df1ed50de39e mysqld: 140528 23:04:05 [Note] Plugin 'FEEDBACK' is disabled.
May 28 23:04:05 df1ed50de39e mysqld: 140528 23:04:05 [Note] Server socket created on IP: '0.0.0.0'.
May 28 23:04:05 df1ed50de39e mysqld: 140528 23:04:05 [Note] Event Scheduler: Loaded 0 events
May 28 23:04:05 df1ed50de39e mysqld: 140528 23:04:05 [Note] /usr/sbin/mysqld: ready for connections.
May 28 23:04:05 df1ed50de39e mysqld: Version: '5.5.37-MariaDB-1~trusty-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
May 28 23:04:44 df1ed50de39e mysqld: 140528 23:04:44 [Note] /usr/sbin/mysqld: Normal shutdown
May 28 23:04:44 df1ed50de39e mysqld: 
May 28 23:04:44 df1ed50de39e mysqld: 140528 23:04:44 [Note] Event Scheduler: Purging the queue. 0 events
May 28 23:04:44 df1ed50de39e mysqld: 140528 23:04:44  InnoDB: Starting shutdown...
May 28 23:04:45 df1ed50de39e mysqld: 140528 23:04:45  InnoDB: Shutdown completed; log sequence number 1597945
May 28 23:04:45 df1ed50de39e mysqld: 140528 23:04:45 [Note] /usr/sbin/mysqld: Shutdown complete
May 28 23:04:45 df1ed50de39e mysqld: 
May 28 23:04:45 df1ed50de39e mysqld_safe: mysqld from pid file /var/run/mysqld/mysqld.pid ended
root@69f7d4b0dcd8:/# 
```

I'd be interested if you figured out exactly what was going on. But I am happy switching to devicemapper as a workaround to this. As far as I am concerned it is a bug in docker.

**Comment by Painted-Fox** [comment]
@richardcrichardc My question seems to not apply here.  I produced the error message an entirely different way.

This is odd.  I'm using _aufs_ on Ubuntu with the same Docker version, but I can't reproduce your error.

```
fox@Squeak:~$ docker info
Containers: 87
Images: 262
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 463
Execution Driver: native-0.2
Kernel Version: 3.11.0-12-generic
WARNING: No swap limit support
```

The only thing I can think of is that I'm running on a different kernel version.  I wonder if I can reproduce this if I upgrade to the latest Ubuntu.

I read through the bug you linked.  It could potentially be the issue.  If so, maybe there's some permissions I can set to make this work with aufs.

**Comment by zar29** [comment]
I got this to work using @richardcrichardc suggestion, everything works as it should when devicemapper is set as the storage driver.
